name: vakifbank
description: A new Flutter project with clean architecture.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state management
  flutter_bloc: ^8.1.2

  # service locator
  get_it: ^7.2.0

  # network
  dio: ^5.0.2
  retrofit: ^4.0.1

  # local storage
  hive_flutter: ^1.1.0

  # navigation
  go_router: ^6.2.0

  # core utilities
  envied: ^0.3.0
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  #ui utilities
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # development
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  mocktail: ^0.3.0
  retrofit_generator: ^6.0.0+1
  very_good_analysis: ^4.0.0+1

flutter:

  uses-material-design: true

